#include <gfxc.h>

const GfxcInstruction GFXC_INSTRUCTIONS[] = {
	{ "nop", sizeof("nop") - 1, 0, { 0 } },

	{ "jump", sizeof("jump") - 1, 2, { GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "wait", sizeof("wait") - 1, 1, { GFXC_TYPE_FLOAT } },
	{ "sleep", sizeof("sleep") - 1, 0, { 0 } },
	{ "trigger", sizeof("trigger") - 1, 2, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_LABEL } },
	{ "untrigger", sizeof("untrigger") - 1, 0, { 0 } },
	{ "freeze", sizeof("freeze") - 1, 0, { 0 } },
	{ "return", sizeof("ret") - 1, 0, { 0 } },

	{ "set", sizeof("set") - 1, 2, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT } },
	{ "add", sizeof("add") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "sub", sizeof("sub") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "xor", sizeof("xor") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "or", sizeof("or") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "and", sizeof("and") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "sl", sizeof("sl") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "sr", sizeof("sr") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "mul", sizeof("mul") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "div", sizeof("div") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "rem", sizeof("rem") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },

	{ "setr", sizeof("setr") - 1, 3, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT } },

	{ "beq", sizeof("beq") - 1, 4, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "bne", sizeof("bne") - 1, 4, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "blt", sizeof("blt") - 1, 4, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "ble", sizeof("ble") - 1, 4, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "bgt", sizeof("bgt") - 1, 4, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "bge", sizeof("bge") - 1, 4, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT  } },

	{ "fset", sizeof("fset") - 1, 2, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT } },
	{ "fadd", sizeof("fadd") - 1, 3, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "fsub", sizeof("fsub") - 1, 3, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "fmul", sizeof("fmul") - 1, 3, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "fdiv", sizeof("fdiv") - 1, 3, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "fmod", sizeof("fmod") - 1, 3, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },

	{ "fsetr", sizeof("fsetr") - 1, 3, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },

	{ "fcfi", sizeof("fcfi") - 1, 2, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_INT_REGISTER } },
	{ "fc2i", sizeof("fc2i") - 1, 2, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_FLOAT_REGISTER } },

	{ "fsin", sizeof("fsin") - 1, 2, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT } },
	{ "fasin", sizeof("fasin") - 1, 2, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT } },
	{ "fcos", sizeof("fcos") - 1, 2, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT } },
	{ "facos", sizeof("facos") - 1, 2, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT } },
	{ "ftan", sizeof("ftan") - 1, 2, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT } },
	{ "fatan", sizeof("fatan") - 1, 2, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT } },
	{ "fatan2", sizeof("fatan2") - 1, 3, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },

	{ "fbeq", sizeof("fbeq") - 1, 4, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "fbne", sizeof("fbne") - 1, 4, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "fblt", sizeof("fblt") - 1, 4, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "fble", sizeof("fble") - 1, 4, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "fbgt", sizeof("fbgt") - 1, 4, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },
	{ "fbge", sizeof("fbge") - 1, 4, { GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT } },

	{ "region", sizeof("region") - 1, 1, { GFXC_TYPE_REGION } },
	{ "regionr", sizeof("regionr") - 1, 2, { GFXC_TYPE_REGION, GFXC_TYPE_REGION } },
	{ "render", sizeof("render") - 1, 1, { GFXC_TYPE_INT } },
	{ "layer", sizeof("layer") - 1, 1, { GFXC_TYPE_INT } },
	{ "filter", sizeof("filter") - 1, 1, { GFXC_TYPE_INT } },
	{ "wrap", sizeof("wrap") - 1, 2, { GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "flags", sizeof("flags") - 1, 2, { GFXC_TYPE_INT, GFXC_TYPE_BOOL } },
	{ "blend.rgb", sizeof("blend.rgb") - 1, 2, { GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "blend.a", sizeof("blend.a") - 1, 2, { GFXC_TYPE_INT, GFXC_TYPE_INT } },
	{ "blendop.rgb", sizeof("blendop.rgb") - 1, 1, { GFXC_TYPE_INT } },
	{ "blendop.a", sizeof("blendop.a") - 1, 1, { GFXC_TYPE_INT } },
	{ "depthf", sizeof("depthf") - 1, 1, { GFXC_TYPE_INT } },
	{ "cull", sizeof("cull") - 1, 1, { GFXC_TYPE_INT } },

	{ "anchor", sizeof("anchor") - 1, 1, { GFXC_TYPE_INT } },
	{ "origin", sizeof("origin") - 1, 1, { GFXC_TYPE_INT } },
	{ "offset", sizeof("offset") - 1, 2, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "pos", sizeof("pos") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "rot", sizeof("rot") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "scale", sizeof("scale") - 1, 2, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "rgb.a", sizeof("rgb.a") - 1, 1, { GFXC_TYPE_HEX } },
	{ "rgb.b", sizeof("rgb.b") - 1, 1, { GFXC_TYPE_HEX } },
	{ "a.a", sizeof("a.a") - 1, 1, { GFXC_TYPE_FLOAT } },
	{ "a.b", sizeof("a.b") - 1, 1, { GFXC_TYPE_FLOAT } },
	{ "lvel", sizeof("lvel") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "avel", sizeof("avel") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "scroll.x", sizeof("scroll.x") - 1, 1, { GFXC_TYPE_FLOAT } },
	{ "scroll.y", sizeof("scroll.y") - 1, 1, { GFXC_TYPE_FLOAT } },
	{ "uv", sizeof("uv") - 1, 2, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "tw.offset", sizeof("tw.offset") - 1, 4, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.pos", sizeof("tw.pos") - 1, 5, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.rot", sizeof("tw.rot") - 1, 5, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.scale", sizeof("tw.scale") - 1, 4, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.rgb.a", sizeof("tw.rgb.a") - 1, 3, { GFXC_TYPE_HEX, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.rgb.b", sizeof("tw.rgb.b") - 1, 3, { GFXC_TYPE_HEX, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.a.a", sizeof("tw.a.a") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.a.b", sizeof("tw.a.b") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.lvel", sizeof("tw.lvel") - 1, 5, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.avel", sizeof("tw.avel") - 1, 5, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.scroll.x", sizeof("tw.scroll.x") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.scroll.y", sizeof("tw.scroll.y") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "tw.uv", sizeof("tw.uv") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT } },
	{ "fade", sizeof("fade") - 1, 3, { GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "grad", sizeof("grad") - 1, 1, { GFXC_TYPE_INT } },

	{ "new", sizeof("new") - 1, 2, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_SCRIPT } },
	{ "newpos", sizeof("newpos") - 1, 5, { GFXC_TYPE_INT_REGISTER, GFXC_TYPE_SCRIPT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "detnew", sizeof("detnew") - 1, 1, { GFXC_TYPE_SCRIPT } },
	{ "detnewpos", sizeof("detnewpos") - 1, 4, { GFXC_TYPE_SCRIPT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT } },
	{ "inh", sizeof("inh") - 1, 0, { 0 } },
	{ "kill", sizeof("kill") - 1, 1, { GFXC_TYPE_INT_REGISTER } },

	// Tail, for bounds checking
	{ 0 }
};
