#include <gfxc.h>

#define GFXC_INSTRUCTION_NO_ARGS(id) { (id), sizeof((id)) - 1, 0, { 0 } }
#define GFXC_INSTRUCTION_ONE_ARG(id, a0) { (id), sizeof((id)) - 1, 1, { a0 } }
#define GFXC_INSTRUCTION_TWO_ARGS(id, a0, a1) { (id), sizeof((id)) - 1, 2, { a0, a1 } }
#define GFXC_INSTRUCTION_THREE_ARGS(id, a0, a1, a2) { (id), sizeof((id)) - 1, 3, { a0, a1, a2 } }
#define GFXC_INSTRUCTION_FOUR_ARGS(id, a0, a1, a2, a3) { (id), sizeof((id)) - 1, 4, { a0, a1, a2, a3 } }
#define GFXC_INSTRUCTION_FIVE_ARGS(id, a0, a1, a2, a3, a4) { (id), sizeof((id)) - 1, 5, { a0, a1, a2, a3, a4 } }
#define GFXC_INSTRUCTION_SIX_ARGS(id, a0, a1, a2, a3, a4, a5) { (id), sizeof((id)) - 1, 6, { a0, a1, a2, a3, a4, a5 } }
#define GFXC_INSTRUCTION_SEVEN_ARGS(id, a0, a1, a2, a3, a4, a5, a6) \
	{ (id), sizeof((id)) - 1, 7, { a0, a1, a2, a3, a4, a5, a6 } }
#define GFXC_INSTRUCTION_EIGHT_ARGS(id, a0, a1, a2, a3, a4, a5, a6, a7) \
	{ (id), sizeof((id)) - 1, 8, { a0, a1, a2, a3, a4, a5, a6, a7 } }
#define GFXC_INSTRUCTION_NINE_ARGS(id, a0, a1, a2, a3, a4, a5, a6, a7, a8) \
	{ (id), sizeof((id)) - 1, 9, { a0, a1, a2, a3, a4, a5, a6, a7, a8 } }
#define GFXC_INSTRUCTION_TEN_ARGS(id, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9) \
	{ (id), sizeof((id)) - 1, 10, { a0, a1, a2, a3, a4, a5, a6, a7, a8, a9 } }

const GfxcInstruction GFXC_INSTRUCTIONS[] = {
	GFXC_INSTRUCTION_NO_ARGS("nop"),

	GFXC_INSTRUCTION_TWO_ARGS("jump", GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_ONE_ARG("wait", GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_NO_ARGS("sleep"),
	GFXC_INSTRUCTION_TWO_ARGS("trigger", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_LABEL),
	GFXC_INSTRUCTION_NO_ARGS("untrigger"),
	GFXC_INSTRUCTION_NO_ARGS("freeze"),
	GFXC_INSTRUCTION_NO_ARGS("return"),

	GFXC_INSTRUCTION_TWO_ARGS("set", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("add", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("sub", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("xor", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("or", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("and", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("sl", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("sr", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("mul", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("div", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("rem", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),

	GFXC_INSTRUCTION_THREE_ARGS("setr", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_INT),

	GFXC_INSTRUCTION_FOUR_ARGS("beq", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("bne", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("blt", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("ble", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("bgt", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("bge", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_INT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),

	GFXC_INSTRUCTION_TWO_ARGS("fset", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("fadd", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("fsub", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("fmul", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("fdiv", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("fmod", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),

	GFXC_INSTRUCTION_THREE_ARGS("fsetr", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),

	GFXC_INSTRUCTION_TWO_ARGS("fcfi", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_INT_REGISTER),
	GFXC_INSTRUCTION_TWO_ARGS("fc2i", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_FLOAT_REGISTER),

	GFXC_INSTRUCTION_TWO_ARGS("fsin", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_TWO_ARGS("fasin", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_TWO_ARGS("fcos", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_TWO_ARGS("facos", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_TWO_ARGS("ftan", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_TWO_ARGS("fatan", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("fatan2", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),

	GFXC_INSTRUCTION_FOUR_ARGS("fbeq", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("fbne", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("fblt", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("fble", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("fbgt", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("fbge", GFXC_TYPE_FLOAT_REGISTER, GFXC_TYPE_FLOAT, GFXC_TYPE_LABEL, GFXC_TYPE_FLOAT),

	GFXC_INSTRUCTION_ONE_ARG("region", GFXC_TYPE_REGION),
	GFXC_INSTRUCTION_TWO_ARGS("regionr", GFXC_TYPE_REGION, GFXC_TYPE_REGION),
	GFXC_INSTRUCTION_ONE_ARG("render", GFXC_TYPE_INT),
	GFXC_INSTRUCTION_ONE_ARG("layer", GFXC_TYPE_INT),
	GFXC_INSTRUCTION_ONE_ARG("filter", GFXC_TYPE_INT),
	GFXC_INSTRUCTION_TWO_ARGS("wrap", GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_TWO_ARGS("flags", GFXC_TYPE_INT, GFXC_TYPE_BOOL),
	GFXC_INSTRUCTION_TWO_ARGS("blend.rgb", GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_TWO_ARGS("blend.a", GFXC_TYPE_INT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_ONE_ARG("blendop.rgb", GFXC_TYPE_INT),
	GFXC_INSTRUCTION_ONE_ARG("blendop.a", GFXC_TYPE_INT),
	GFXC_INSTRUCTION_ONE_ARG("depthf", GFXC_TYPE_INT),
	GFXC_INSTRUCTION_ONE_ARG("cull", GFXC_TYPE_INT),

	GFXC_INSTRUCTION_ONE_ARG("anchor", GFXC_TYPE_INT),
	GFXC_INSTRUCTION_ONE_ARG("origin", GFXC_TYPE_INT),
	GFXC_INSTRUCTION_TWO_ARGS("offset", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("pos", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("rot", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_TWO_ARGS("scale", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_ONE_ARG("rgb.a", GFXC_TYPE_HEX),
	GFXC_INSTRUCTION_ONE_ARG("rgb.b", GFXC_TYPE_HEX),
	GFXC_INSTRUCTION_ONE_ARG("a.a", GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_ONE_ARG("a.b", GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("lvel", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_THREE_ARGS("avel", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_ONE_ARG("scroll.u", GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_ONE_ARG("scroll.v", GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_TWO_ARGS("uvA", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_TWO_ARGS("uvB", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_FOUR_ARGS("tw.offset", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_FIVE_ARGS("tw.pos", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_FIVE_ARGS("tw.rot", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_FOUR_ARGS("tw.scale", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("tw.rgb.a", GFXC_TYPE_FLOAT, GFXC_TYPE_HEX, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("tw.rgb.b", GFXC_TYPE_FLOAT, GFXC_TYPE_HEX, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("tw.a.a", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("tw.a.b", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_FIVE_ARGS("tw.lvel", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_FIVE_ARGS("tw.avel", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("tw.scroll.u", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_THREE_ARGS("tw.scroll.v", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_FOUR_ARGS("tw.uvA", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_FOUR_ARGS("tw.uvB", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_INT),
	GFXC_INSTRUCTION_TWO_ARGS("fade", GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_ONE_ARG("grad", GFXC_TYPE_INT),

	GFXC_INSTRUCTION_TWO_ARGS("new", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_SCRIPT),
	GFXC_INSTRUCTION_FIVE_ARGS("newpos", GFXC_TYPE_INT_REGISTER, GFXC_TYPE_SCRIPT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_ONE_ARG("detnew", GFXC_TYPE_SCRIPT),
	GFXC_INSTRUCTION_FOUR_ARGS("detnewpos", GFXC_TYPE_SCRIPT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT, GFXC_TYPE_FLOAT),
	GFXC_INSTRUCTION_NO_ARGS("inh"),
	GFXC_INSTRUCTION_ONE_ARG("kill", GFXC_TYPE_INT_REGISTER),

	// Tail, for bounds checking
	{ 0 }
};
