#include <gfxc.h>

#define GFXC_SYMBOL_REGION(id, v) { (id), sizeof((id)) - 1, { .region = { GFXC_TYPE_REGION, (v) } } }
#define GFXC_SYMBOL_INT(id, v) { (id), sizeof((id)) - 1, { .intv = { GFXC_TYPE_INT, (v) } } }
#define GFXC_SYMBOL_FLOAT(id, v) { (id), sizeof((id)) - 1, { .floatv = { GFXC_TYPE_FLOAT, (v) } } }
#define GFXC_SYMBOL_FLOAT(id, v) { (id), sizeof((id)) - 1, { .floatv = { GFXC_TYPE_FLOAT, (v) } } }
#define GFXC_SYMBOL_INT_REGISTER(id, r) { (id), sizeof((id)) - 1, { .reg = { GFXC_TYPE_INT_REGISTER, (r) } } }
#define GFXC_SYMBOL_FLOAT_REGISTER(id, r) { (id), sizeof((id)) - 1, { .reg = { GFXC_TYPE_FLOAT_REGISTER, (r) } } }

const GfxcSymbol GFXC_DEFAULT_SYMBOLS[] = {
	// To denote an region that is default during VM launch - the region that doesn't exist
	GFXC_SYMBOL_REGION("REGION_NONE", 0),

	// Math constants
	GFXC_SYMBOL_FLOAT("M_PI", 3.14159265358979323846f),
	GFXC_SYMBOL_FLOAT("M_DEG2RAD", 3.14159265358979323846f / 180.0f),
	GFXC_SYMBOL_FLOAT("M_RAD2DEG", 180.0f / 3.14159265358979323846f),

	// Texture formats
	GFXC_SYMBOL_INT("TEXTURE_FORMAT_RGBA8", 0),
	GFXC_SYMBOL_INT("TEXTURE_FORMAT_R8", 1),
	GFXC_SYMBOL_INT("TEXTURE_FORMAT_DEPTH24_STENCIL8", 2),

	// Texture filtering
	GFXC_SYMBOL_INT("TEXTURE_FILTER_NEAREST", 0),
	GFXC_SYMBOL_INT("TEXTURE_FILTER_LINEAR", 1),

	// Texture repeating
	GFXC_SYMBOL_INT("TEXTURE_WRAP_CLAMP", 0),
	GFXC_SYMBOL_INT("TEXTURE_WRAP_REPEAT", 1),
	GFXC_SYMBOL_INT("TEXTURE_WRAP_MIRROR", 2),

	// Origin
	GFXC_SYMBOL_INT("ORIGIN_PARENT", 0),
	GFXC_SYMBOL_INT("ORIGIN_OBJECT", 1),
	GFXC_SYMBOL_INT("ORIGIN_SURFACE", 2),

	// Anchor
	GFXC_SYMBOL_INT("ANCHOR_TOP_LEFT", 0 | 0),
	GFXC_SYMBOL_INT("ANCHOR_TOP_MIDDLE", 0 | 1),
	GFXC_SYMBOL_INT("ANCHOR_TOP_RIGHT", 0 | 2),
	GFXC_SYMBOL_INT("ANCHOR_MIDDLE_LEFT", 4 | 0),
	GFXC_SYMBOL_INT("ANCHOR_CENTER", 4 | 1),
	GFXC_SYMBOL_INT("ANCHOR_MIDDLE_RIGHT", 4 | 2),
	GFXC_SYMBOL_INT("ANCHOR_BOTTOM_LEFT", 8 | 0),
	GFXC_SYMBOL_INT("ANCHOR_BOTTOM_MIDDLE", 8 | 1),
	GFXC_SYMBOL_INT("ANCHOR_BOTTOM_RIGHT", 8 | 2),

	// Flags
	GFXC_SYMBOL_INT("FLAG_VISIBLE", (1 << 0)),
	GFXC_SYMBOL_INT("FLAG_FLIP_X", (1 << 1)),
	GFXC_SYMBOL_INT("FLAG_FLIP_Y", (1 << 2)),
	GFXC_SYMBOL_INT("FLAG_AUTOTURN", (1 << 3)),
	GFXC_SYMBOL_INT("FLAG_BLEND", (1 << 4)),
	GFXC_SYMBOL_INT("FLAG_DEPTH", (1 << 5)),
	GFXC_SYMBOL_INT("FLAG_WRITE_DEPTH", (1 << 6)),
	GFXC_SYMBOL_INT("FLAG_CULL", (1 << 7)),
	GFXC_SYMBOL_INT("FLAG_FADE", (1 << 8)),
	GFXC_SYMBOL_INT("FLAG_INTERPOLATE", (1 << 9)),
	GFXC_SYMBOL_INT("FLAG_INTERPOLATE_UV", (1 << 10)),

	// Render
	GFXC_SYMBOL_INT("RENDER_PIXEL", 0),
	GFXC_SYMBOL_INT("RENDER_2D", 1),
	GFXC_SYMBOL_INT("RENDER_BILLBOARD", 2),
	GFXC_SYMBOL_INT("RENDER_BILLBOARD_SCALED", 3),
	GFXC_SYMBOL_INT("RENDER_3D", 4),
	GFXC_SYMBOL_INT("RENDER_3D_SCALED", 5),

	// Blend
	GFXC_SYMBOL_INT("BLEND_ZERO", 0),
	GFXC_SYMBOL_INT("BLEND_ONE", 1),
	GFXC_SYMBOL_INT("BLEND_SRC_COLOR", 2),
	GFXC_SYMBOL_INT("BLEND_INV_SRC_COLOR", 3),
	GFXC_SYMBOL_INT("BLEND_SRC_ALPHA", 4),
	GFXC_SYMBOL_INT("BLEND_INV_SRC_ALPHA", 5),
	GFXC_SYMBOL_INT("BLEND_DEST_ALPHA", 6),
	GFXC_SYMBOL_INT("BLEND_INV_DEST_ALPHA", 7),
	GFXC_SYMBOL_INT("BLEND_DEST_COLOR", 8),
	GFXC_SYMBOL_INT("BLEND_INV_DEST_COLOR", 9),

	// Blend op
	GFXC_SYMBOL_INT("BLEND_OP_ADD", 0),
	GFXC_SYMBOL_INT("BLEND_OP_SUB", 1),
	GFXC_SYMBOL_INT("BLEND_OP_REVERSE_SUB", 2),
	GFXC_SYMBOL_INT("BLEND_OP_MIN", 3),
	GFXC_SYMBOL_INT("BLEND_OP_MAX", 4),

	// Comparison
	GFXC_SYMBOL_INT("COMPARISON_NEVER", 0),
	GFXC_SYMBOL_INT("COMPARISON_LESS", 1),
	GFXC_SYMBOL_INT("COMPARISON_EQUAL", 2),
	GFXC_SYMBOL_INT("COMPARISON_LEQUAL", 3),
	GFXC_SYMBOL_INT("COMPARISON_GREATER", 4),
	GFXC_SYMBOL_INT("COMPARISON_NEQUAL", 5),
	GFXC_SYMBOL_INT("COMPARISON_GEQUAL", 6),
	GFXC_SYMBOL_INT("COMPARISON_ALWAYS", 7),

	// Cull
	GFXC_SYMBOL_INT("CULL_BACK", 0),
	GFXC_SYMBOL_INT("CULL_FRONT", 1),
	GFXC_SYMBOL_INT("CULL_BOTH", 2),

	// Interpolation
	GFXC_SYMBOL_INT("INTERPOLATION_LINEAR", 0),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_QUAD", 1),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_OUT_QUAD", 2),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_OUT_QUAD", 3),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_CUBIC", 4),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_OUT_CUBIC", 5),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_OUT_CUBIC", 6),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_EXP", 7),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_OUT_EXP", 8),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_OUT_EXP", 9),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_BACK", 10),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_OUT_BACK", 11),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_OUT_BACK", 12),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_ELASTIC", 13),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_OUT_ELASTIC", 14),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_OUT_ELASTIC", 15),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_BOUNCE", 16),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_OUT_BOUNCE", 17),
	GFXC_SYMBOL_INT("INTERPOLATION_EASE_IN_OUT_BOUNCE", 18),

	// Gradient
	GFXC_SYMBOL_INT("GRADIENT_A", 0),
	GFXC_SYMBOL_INT("GRADIENT_B", 1),
	GFXC_SYMBOL_INT("GRADIENT_AB", 2),
	GFXC_SYMBOL_INT("GRADIENT_BA", 3),

	// Registers
	GFXC_SYMBOL_INT_REGISTER("x0", 0),
	GFXC_SYMBOL_INT_REGISTER("x1", 1),
	GFXC_SYMBOL_INT_REGISTER("x2", 2),
	GFXC_SYMBOL_INT_REGISTER("x3", 3),
	GFXC_SYMBOL_INT_REGISTER("x4", 4),
	GFXC_SYMBOL_INT_REGISTER("x5", 5),
	GFXC_SYMBOL_INT_REGISTER("x6", 6),
	GFXC_SYMBOL_INT_REGISTER("x7", 7),
	GFXC_SYMBOL_INT_REGISTER("x8", 8),
	GFXC_SYMBOL_INT_REGISTER("x9", 9),
	GFXC_SYMBOL_INT_REGISTER("x10", 10),
	GFXC_SYMBOL_INT_REGISTER("x11", 11),
	GFXC_SYMBOL_INT_REGISTER("x12", 12),
	GFXC_SYMBOL_INT_REGISTER("x13", 13),
	GFXC_SYMBOL_INT_REGISTER("x14", 14),
	GFXC_SYMBOL_INT_REGISTER("x15", 15),
	GFXC_SYMBOL_INT_REGISTER("x16", 16),
	GFXC_SYMBOL_INT_REGISTER("x17", 17),
	GFXC_SYMBOL_INT_REGISTER("x18", 18),
	GFXC_SYMBOL_INT_REGISTER("x19", 19),
	GFXC_SYMBOL_INT_REGISTER("x20", 20),
	GFXC_SYMBOL_INT_REGISTER("x21", 21),
	GFXC_SYMBOL_INT_REGISTER("x22", 22),
	GFXC_SYMBOL_INT_REGISTER("x23", 23),
	GFXC_SYMBOL_INT_REGISTER("x24", 24),
	GFXC_SYMBOL_INT_REGISTER("x25", 25),
	GFXC_SYMBOL_INT_REGISTER("x26", 26),
	GFXC_SYMBOL_INT_REGISTER("x27", 27),
	GFXC_SYMBOL_INT_REGISTER("x28", 28),
	GFXC_SYMBOL_INT_REGISTER("x29", 29),
	GFXC_SYMBOL_INT_REGISTER("x30", 30),
	GFXC_SYMBOL_INT_REGISTER("x31", 31),

	GFXC_SYMBOL_FLOAT_REGISTER("f0", 0),
	GFXC_SYMBOL_FLOAT_REGISTER("f1", 1),
	GFXC_SYMBOL_FLOAT_REGISTER("f2", 2),
	GFXC_SYMBOL_FLOAT_REGISTER("f3", 3),
	GFXC_SYMBOL_FLOAT_REGISTER("f4", 4),
	GFXC_SYMBOL_FLOAT_REGISTER("f5", 5),
	GFXC_SYMBOL_FLOAT_REGISTER("f6", 6),
	GFXC_SYMBOL_FLOAT_REGISTER("f7", 7),
	GFXC_SYMBOL_FLOAT_REGISTER("f8", 8),
	GFXC_SYMBOL_FLOAT_REGISTER("f9", 9),
	GFXC_SYMBOL_FLOAT_REGISTER("f10", 10),
	GFXC_SYMBOL_FLOAT_REGISTER("f11", 11),
	GFXC_SYMBOL_FLOAT_REGISTER("f12", 12),
	GFXC_SYMBOL_FLOAT_REGISTER("f13", 13),
	GFXC_SYMBOL_FLOAT_REGISTER("f14", 14),
	GFXC_SYMBOL_FLOAT_REGISTER("f15", 15),
	GFXC_SYMBOL_FLOAT_REGISTER("f16", 16),
	GFXC_SYMBOL_FLOAT_REGISTER("f17", 17),
	GFXC_SYMBOL_FLOAT_REGISTER("f18", 18),
	GFXC_SYMBOL_FLOAT_REGISTER("f19", 19),
	GFXC_SYMBOL_FLOAT_REGISTER("f20", 20),
	GFXC_SYMBOL_FLOAT_REGISTER("f21", 21),
	GFXC_SYMBOL_FLOAT_REGISTER("f22", 22),
	GFXC_SYMBOL_FLOAT_REGISTER("f23", 23),
	GFXC_SYMBOL_FLOAT_REGISTER("f24", 24),
	GFXC_SYMBOL_FLOAT_REGISTER("f25", 25),
	GFXC_SYMBOL_FLOAT_REGISTER("f26", 26),
	GFXC_SYMBOL_FLOAT_REGISTER("f27", 27),
	GFXC_SYMBOL_FLOAT_REGISTER("f28", 28),
	GFXC_SYMBOL_FLOAT_REGISTER("f29", 29),
	GFXC_SYMBOL_FLOAT_REGISTER("f30", 30),
	GFXC_SYMBOL_FLOAT_REGISTER("f31", 31),

	// Tail, for bounds checking
	{ 0 }
};

#undef GFXC_SYMBOL_FLOAT_REGISTER
#undef GFXC_SYMBOL_INT_REGISTER
#undef GFXC_SYMBOL_FLOAT
#undef GFXC_SYMBOL_INT
#undef GFXC_SYMBOL_REGION
