#ifndef AST_H
#define AST_H

#include <defines.h>

typedef enum {
	AST_NODE_TYPE_NONE,

	AST_NODE_TYPE_TEXTURE,
	AST_NODE_TYPE_REGION,
	AST_NODE_TYPE_CONST,

	AST_NODE_TYPE_SCRIPT,
	AST_NODE_TYPE_LABEL,
	AST_NODE_TYPE_TIME_LABEL,
	AST_NODE_TYPE_INSTRUCTION,
	AST_NODE_TYPE_INT_REGISTER,
	AST_NODE_TYPE_FLOAT_REGISTER,

	AST_NODE_TYPE_IDENTIFIER,
	AST_NODE_TYPE_INT_LITERAL,
	AST_NODE_TYPE_FLOAT_LITERAL,
	AST_NODE_TYPE_HEX_LITERAL,
	AST_NODE_TYPE_STRING_LITERAL,

	AST_NODE_TYPE_COMPILER_FUNCTION,

	AST_NODE_TYPE_ENUM_COUNT
} AstNodeType;

#endif // AST_H
